### ISSUE TITLE
Simple  `stu` to build the handbook fails

### ISSUE THREAD

**Issue by jmon12** [kunegis/konect-handbook#3]
I'm trying to build the handbook using my freshly installed `stu` (version 2.6.13, installed from the AUR package). It fails, here is the debug output of `stu`:

```
DEBUG  loop
DEBUG     ROOT connect @main
DEBUG        @main connect -% konect-handbook.pdf
DEBUG           konect-handbook.pdf connect [FILES]
DEBUG              [FILES] connect -* FILES
DEBUG                 FILES connect -t texdep
DEBUG                 FILES disconnect -t texdep
DEBUG                 FILES connect konect-handbook.tex
DEBUG                 FILES disconnect konect-handbook.tex
DEBUG                 FILES connect texdep
DEBUG                    texdep connect stu-utils/texdep
main.stu:93:15: no rule to build stu-utils/texdep, needed by texdep
main.stu:44:13: texdep is needed by FILES
main.stu:20:24: [FILES] is needed by konect-handbook.pdf
main.stu:12:10: konect-handbook.pdf is needed by @main
``` 

I'm totally new to `stu` and all of your great work. I'll keep this post updated if I investigate further and find a solution.

**Comment by kunegis** [comment]
Hello
It seems the "texdep" tool was not found.  I guess you haven't yet downloaded the stu-utils package?  Just do this:
- Get https://github.com/kunegis/stu-utils from Github
- Symlink stu-utils within su-handbook to the just cloned stu-utils repo.
That should do it.
